#! /usr/bin/env ruby

unless ARGV.length == 1
  warn "Usage: #{$0} <scenario>"
  exit 1
end

require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path '../lib', __FILE__
require 'scenario'

scenario_path = ARGV.first
Scenario.run(scenario_path)
