#! /usr/bin/env ruby

unless ARGV.length == 1
  warn "Usage: #{$0} <scenario>"
  exit 1
end

require 'bundler/setup'
require 'pry'

$LOAD_PATH.unshift File.expand_path '../lib', __FILE__
# $LOAD_PATH.unshift File.expand_path '../scenarios', __FILE__

require 'scenario'

PROMPT = proc { |target,_,_| "#{target.__name} > " }

Scenario.run(ARGV.first) do |scenario|
  Pry.start(scenario, prompt: PROMPT)
end
